name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t weather-app_app .

    - name: Set Docker image tag as an output
      id: set-image-tag
      run: echo "DOCKER_IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

    - name: Use Docker image tag
      run: echo "Docker image tag is ${{ steps.set-image-tag.outputs.DOCKER_IMAGE_TAG }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u chandanaramu --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag chandanaramu/weather-app_app:${{ github.sha }} chandanaramu/weather-app_app:latest
          docker push chandanaramu/weather-app_app:${{ github.sha }}
          docker push chandanaramu/weather-app_app:latest

      - name: Deploy to Docker environment
        run: |
          docker pull chandanaramu/weather-app_app:${{ github.sha }}
          docker stop weather-app || true
          docker rm weather-app || true
          docker run -d --name weather-app -p 3000:3000 chandanaramu/weather-app_app:${{ github.sha }}
