name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t docker.io/weather-app_app:latest -t docker.io/weather-app_app:${{ github.sha }} .
        docker buildx imagetools create --tag docker.io/weather-app_app:latest --tag docker.io/weather-app_app:${{ github.sha }} --name weather-app
      env:
        DOCKER_CLI_ACI_OFFICIAL: 1
        BUILDKIT_PROGRESS: plain

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image to Docker Hub
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t docker.io/weather-app_app:latest -t docker.io/weather-app_app:${{ github.sha }} .
        docker buildx imagetools create --tag docker.io/weather-app_app:latest --tag docker.io/weather-app_app:${{ github.sha }} --name weather-app
        docker push docker.io/weather-app_app:latest
        docker push docker.io/weather-app_app:${{ github.sha }}

    - name: Deploy to Docker environment
      run: |
        docker buildx create --use
        docker pull docker.io/weather-app_app:latest
        docker tag docker.io/weather-app_app:latest docker.io/weather-app_app:${{ github.sha }}
        docker run -d --name weather-app -p 3000:3000 docker.io/weather-app_app:${{ github.sha }}
