name: CICD

on:
  push:
    branches: [master, testbranch]

jobs:
  Create-Release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Log branch name
        run: |
          echo "Current branch: ${{ github.ref }}"
        
      - name: New Release Publish
        if: github.ref == 'refs/heads/master'
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

    outputs:
      release_id: ${{ steps.new_publish.outputs.id }}
      release_name: ${{ steps.new_publish.outputs.tag_name }}
