name: CICD

on:
  push:
    branches: []

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image.outputs.IMAGE }}
    steps:
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          REPOSITORY: kanso-ops-automations
        run: |
          # Perform the build and tag operations here
          # For demonstration purposes, set a dummy value for the image
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-')
          COMMIT_ID=${{ github.sha }}
          IMAGE_TAG=$BRANCH_NAME-$COMMIT_ID
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      - name : Set output 
        id: image
        run : echo "::set-output name=IMAGE::${env.IMAGE_TAG}"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Use output from previous job
        run: |
          echo "Image: ${{ needs.build-and-deploy.outputs.image }}"
