name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: |
        docker build -t weather-app .
        docker images

    - name: Test the application
      run: docker run --rm -p 3000:3000 weather-app npm test

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name : version
      run : docker --version

    - name: Tag Docker image
      run: docker tag weather-app ${{ secrets.DOCKER_USERNAME }}/weather-app:latest

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/weather-app:latest

    - name: Deploy to Docker environment
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/weather-app:latest
        docker stop weather-app || true
        docker rm weather-app || true
        docker run -d --name weather-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/weather-app:latest
