name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t weather-app_app .

    - name: Set Docker image tag as an output
      id: set-image-tag
      run: echo "DOCKER_IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

    # Use the output in the next step or job
    - name: Use Docker image tag
      run: echo "Docker image tag is ${{ steps.set-image-tag.outputs.DOCKER_IMAGE_TAG }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set up Docker
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        push: true
        tags: docker.io/weather-app_app:latest, docker.io/weather-app_app:${{ github.sha }}

    - name: Deploy to Docker environment
      run: |
        docker pull docker.io/weather-app_app:${{ github.sha }}
        docker run -d --name weather-app -p 3000:3000 docker.io/weather-app_app:${{ github.sha }}
