name: CICD

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-image.outputs.IMAGE }}
    steps:
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          REPOSITORY: kanso-ops-automations
          IMAGE_TAG: latest
        run: |
          # Perform the build and tag operations here
          # For demonstration purposes, echo a dummy value
          echo "chandana" >> $GITHUB_ENV
          echo "::set-output name=IMAGE::chandana"

  deploy :
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Use output from previous job
        run: |
          echo "Image: ${{ needs.build-and-deploy.outputs.image }}"
