name: CICD

on:
  workflow_dispatch:
  push:
    branches: [master, testbranch]

jobs:
  Create-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Log branch name
        run: |
          echo "Current branch: ${{ github.ref }}"
        
      - name: New Release Publish
        # if: github.ref == 'refs/heads/master'
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
